package net.fellter.vanillavsplus.item;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.fellter.vanillavsplus.VanillaVSPlus;
import net.fellter.vanillavsplus.block.ModBlocks;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ModItemGroups {

    @SuppressWarnings("unused")
    public static final ItemGroup VVSP_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(VanillaVSPlus.MOD_ID, "vvsp"),
            FabricItemGroup.builder().displayName(Text.translatable("itemgroup.vanillavsplus"))
                    .icon(() -> new ItemStack(ModItems.VVSP_TITLE)).entries(((displayContext, entries) -> {

                        entries.add(ModBlocks.VERTICAL_OAK_SLAB);
                        entries.add(ModBlocks.VERTICAL_OAK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_OAK_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_OAK_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_OAK_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_OAK_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_OAK_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_OAK_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_OAK_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_OAK_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_SPRUCE_SLAB);
                        entries.add(ModBlocks.VERTICAL_SPRUCE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SPRUCE_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_SPRUCE_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SPRUCE_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_SPRUCE_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_SPRUCE_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_SPRUCE_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_SPRUCE_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_SPRUCE_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_BIRCH_SLAB);
                        entries.add(ModBlocks.VERTICAL_BIRCH_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BIRCH_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_BIRCH_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BIRCH_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_BIRCH_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_BIRCH_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_BIRCH_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_BIRCH_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_BIRCH_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_JUNGLE_SLAB);
                        entries.add(ModBlocks.VERTICAL_JUNGLE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_JUNGLE_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_JUNGLE_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_JUNGLE_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_JUNGLE_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_JUNGLE_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_JUNGLE_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_JUNGLE_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_JUNGLE_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_ACACIA_SLAB);
                        entries.add(ModBlocks.VERTICAL_ACACIA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ACACIA_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_ACACIA_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ACACIA_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_ACACIA_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_ACACIA_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_ACACIA_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_ACACIA_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_ACACIA_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_DARK_OAK_SLAB);
                        entries.add(ModBlocks.VERTICAL_DARK_OAK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DARK_OAK_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_DARK_OAK_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DARK_OAK_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_DARK_OAK_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_DARK_OAK_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_DARK_OAK_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_DARK_OAK_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_DARK_OAK_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_MANGROVE_SLAB);
                        entries.add(ModBlocks.VERTICAL_MANGROVE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MANGROVE_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_MANGROVE_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MANGROVE_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_MANGROVE_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_MANGROVE_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_MANGROVE_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_MANGROVE_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_MANGROVE_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_CHERRY_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHERRY_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHERRY_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHERRY_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHERRY_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHERRY_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CHERRY_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CHERRY_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CHERRY_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CHERRY_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_PALE_OAK_SLAB);
                        entries.add(ModBlocks.VERTICAL_PALE_OAK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PALE_OAK_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_PALE_OAK_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PALE_OAK_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_PALE_OAK_WOOD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_PALE_OAK_LOG_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_PALE_OAK_LOG_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_PALE_OAK_WOOD_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_PALE_OAK_WOOD_STAIRS);

                        entries.add(ModBlocks.VERTICAL_BAMBOO_SLAB);
                        entries.add(ModBlocks.VERTICAL_BAMBOO_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BAMBOO_MOSAIC_SLAB);
                        entries.add(ModBlocks.VERTICAL_BAMBOO_MOSAIC_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BAMBOO_BLOCK_SLAB);
                        entries.add(ModBlocks.VERTICAL_BAMBOO_BLOCK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_BAMBOO_BLOCK_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_BAMBOO_BLOCK_STAIRS);

                        entries.add(ModBlocks.VERTICAL_CRIMSON_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRIMSON_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRIMSON_STEM_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRIMSON_STEM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRIMSON_HYPHAE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRIMSON_HYPHAE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CRIMSON_STEM_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CRIMSON_STEM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CRIMSON_HYPHAE_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_CRIMSON_HYPHAE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WARPED_SLAB);
                        entries.add(ModBlocks.VERTICAL_WARPED_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WARPED_STEM_SLAB);
                        entries.add(ModBlocks.VERTICAL_WARPED_STEM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WARPED_HYPHAE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WARPED_HYPHAE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_WARPED_STEM_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_WARPED_STEM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_WARPED_HYPHAE_SLAB);
                        entries.add(ModBlocks.VERTICAL_STRIPPED_WARPED_HYPHAE_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_STONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_STONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_COBBLESTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_COBBLESTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MOSSY_COBBLESTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_MOSSY_COBBLESTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_STONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_STONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_STONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_STONE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRACKED_STONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRACKED_STONE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_STONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_STONE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MOSSY_STONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_MOSSY_STONE_BRICKS_STAIRS);

                        entries.add(ModBlocks.VERTICAL_GRANITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRANITE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_GRANITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_GRANITE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_DIORITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DIORITE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_DIORITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_DIORITE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_ANDESITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_ANDESITE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_ANDESITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_ANDESITE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_COBBLED_DEEPSLATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_COBBLED_DEEPSLATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_DEEPSLATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_DEEPSLATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_DEEPSLATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_DEEPSLATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRACKED_DEEPSLATE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRACKED_DEEPSLATE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_TILES_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_TILES_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRACKED_DEEPSLATE_TILES_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRACKED_DEEPSLATE_TILES_STAIRS);

                        entries.add(ModBlocks.VERTICAL_TUFF_SLAB);
                        entries.add(ModBlocks.VERTICAL_TUFF_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_TUFF_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_TUFF_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_TUFF_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_TUFF_STAIRS);
                        entries.add(ModBlocks.VERTICAL_TUFF_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_TUFF_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_TUFF_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_TUFF_BRICKS_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PACKED_MUD_SLAB);
                        entries.add(ModBlocks.VERTICAL_PACKED_MUD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MUD_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_MUD_BRICKS_STAIRS);

                        entries.add(ModBlocks.VERTICAL_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_SANDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_SANDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_SANDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CUT_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CUT_SANDSTONE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_RED_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_SANDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_RED_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_RED_SANDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_RED_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_RED_SANDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CUT_RED_SANDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CUT_RED_SANDSTONE_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_SEA_LANTERN_SLAB);
                        entries.add(ModBlocks.VERTICAL_SEA_LANTERN_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PRISMARINE_SLAB);
                        entries.add(ModBlocks.VERTICAL_PRISMARINE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PRISMARINE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_PRISMARINE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DARK_PRISMARINE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DARK_PRISMARINE_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_NETHERRACK_SLAB);
                        entries.add(ModBlocks.VERTICAL_NETHERRACK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_NETHER_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_NETHER_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRACKED_NETHER_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRACKED_NETHER_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_NETHER_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_NETHER_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_NETHER_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_NETHER_BRICKS_STAIRS);

                        entries.add(ModBlocks.VERTICAL_BASALT_SLAB);
                        entries.add(ModBlocks.VERTICAL_BASALT_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_BASALT_SLAB);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_BASALT_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_BASALT_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_BASALT_STAIRS);

                        entries.add(ModBlocks.VERTICAL_BLACKSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACKSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GILDED_BLACKSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_GILDED_BLACKSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_POLISHED_BLACKSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_POLISHED_BLACKSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_POLISHED_BLACKSTONE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRACKED_POLISHED_BLACKSTONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRACKED_POLISHED_BLACKSTONE_BRICKS_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_END_STONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_END_STONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_END_STONE_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_END_STONE_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPUR_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPUR_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPUR_PILLAR_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPUR_PILLAR_STAIRS);

                        entries.add(ModBlocks.VERTICAL_COAL_SLAB);
                        entries.add(ModBlocks.VERTICAL_COAL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_IRON_SLAB);
                        entries.add(ModBlocks.VERTICAL_IRON_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GOLD_SLAB);
                        entries.add(ModBlocks.VERTICAL_GOLD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_REDSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_REDSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_EMERALD_SLAB);
                        entries.add(ModBlocks.VERTICAL_EMERALD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LAPIS_SLAB);
                        entries.add(ModBlocks.VERTICAL_LAPIS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DIAMOND_SLAB);
                        entries.add(ModBlocks.VERTICAL_DIAMOND_STAIRS);
                        entries.add(ModBlocks.VERTICAL_NETHERITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_NETHERITE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_QUARTZ_SLAB);
                        entries.add(ModBlocks.VERTICAL_QUARTZ_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_QUARTZ_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_QUARTZ_STAIRS);
                        entries.add(ModBlocks.VERTICAL_QUARTZ_BRICKS_SLAB);
                        entries.add(ModBlocks.VERTICAL_QUARTZ_BRICKS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_QUARTZ_PILLAR_SLAB);
                        entries.add(ModBlocks.VERTICAL_QUARTZ_PILLAR_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_QUARTZ_SLAB);
                        entries.add(ModBlocks.VERTICAL_SMOOTH_QUARTZ_STAIRS);

                        entries.add(ModBlocks.VERTICAL_AMETHYST_SLAB);
                        entries.add(ModBlocks.VERTICAL_AMETHYST_STAIRS);

                        entries.add(ModBlocks.VERTICAL_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_EXPOSED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_EXPOSED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WEATHERED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WEATHERED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_OXIDIZED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_OXIDIZED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WAXED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_EXPOSED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_WEATHERED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_CHISELED_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_CHISELED_COPPER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_COPPER_GRATE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_COPPER_GRATE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_CUT_COPPER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WAXED_OXIDIZED_CUT_COPPER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WHITE_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_WHITE_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAY_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAY_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLACK_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACK_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BROWN_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_BROWN_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ORANGE_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_ORANGE_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_YELLOW_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_YELLOW_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIME_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIME_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GREEN_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_GREEN_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CYAN_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_CYAN_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPLE_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPLE_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_WOOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PINK_WOOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_PINK_WOOL_STAIRS);

                        entries.add(ModBlocks.VERTICAL_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WHITE_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_WHITE_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAY_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAY_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLACK_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACK_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BROWN_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_BROWN_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ORANGE_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_ORANGE_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_YELLOW_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_YELLOW_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIME_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIME_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GREEN_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_GREEN_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CYAN_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_CYAN_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPLE_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPLE_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PINK_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_PINK_TERRACOTTA_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WHITE_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_WHITE_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAY_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAY_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLACK_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACK_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BROWN_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_BROWN_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ORANGE_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_ORANGE_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_YELLOW_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_YELLOW_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIME_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIME_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GREEN_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_GREEN_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CYAN_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CYAN_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPLE_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPLE_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_CONCRETE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PINK_CONCRETE_SLAB);
                        entries.add(ModBlocks.VERTICAL_PINK_CONCRETE_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WHITE_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_WHITE_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAY_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAY_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLACK_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACK_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BROWN_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_BROWN_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ORANGE_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_ORANGE_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_YELLOW_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_YELLOW_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIME_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIME_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GREEN_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_GREEN_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CYAN_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_CYAN_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPLE_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPLE_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_CONCRETE_POWDER_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PINK_CONCRETE_POWDER_SLAB);
                        entries.add(ModBlocks.VERTICAL_PINK_CONCRETE_POWDER_STAIRS);

                        entries.add(ModBlocks.VERTICAL_WHITE_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_WHITE_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAY_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAY_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLACK_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACK_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BROWN_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_BROWN_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ORANGE_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_ORANGE_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_YELLOW_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_YELLOW_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIME_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIME_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GREEN_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_GREEN_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CYAN_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_CYAN_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPLE_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPLE_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_GLAZED_TERRACOTTA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PINK_GLAZED_TERRACOTTA_SLAB);
                        entries.add(ModBlocks.VERTICAL_PINK_GLAZED_TERRACOTTA_STAIRS);

                        entries.add(ModBlocks.VERTICAL_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WHITE_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_WHITE_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_GRAY_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAY_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAY_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLACK_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLACK_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BROWN_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_BROWN_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ORANGE_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_ORANGE_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_YELLOW_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_YELLOW_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIME_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIME_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GREEN_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_GREEN_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CYAN_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_CYAN_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_LIGHT_BLUE_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PURPLE_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_PURPLE_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGENTA_STAINED_GLASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PINK_STAINED_GLASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_PINK_STAINED_GLASS_STAIRS);

                        entries.add(ModBlocks.VERTICAL_GRASS_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRASS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PODZOL_SLAB);
                        entries.add(ModBlocks.VERTICAL_PODZOL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MYCELIUM_SLAB);
                        entries.add(ModBlocks.VERTICAL_MYCELIUM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DIRT_PATH_SLAB);
                        entries.add(ModBlocks.VERTICAL_DIRT_PATH_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DIRT_SLAB);
                        entries.add(ModBlocks.VERTICAL_DIRT_STAIRS);
                        entries.add(ModBlocks.VERTICAL_COARSE_DIRT_SLAB);
                        entries.add(ModBlocks.VERTICAL_COARSE_DIRT_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ROOTED_DIRT_SLAB);
                        entries.add(ModBlocks.VERTICAL_ROOTED_DIRT_STAIRS);
                        entries.add(ModBlocks.VERTICAL_FARMLAND_SLAB);
                        entries.add(ModBlocks.VERTICAL_FARMLAND_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MUD_SLAB);
                        entries.add(ModBlocks.VERTICAL_MUD_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CLAY_SLAB);
                        entries.add(ModBlocks.VERTICAL_CLAY_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GRAVEL_SLAB);
                        entries.add(ModBlocks.VERTICAL_GRAVEL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SAND_SLAB);
                        entries.add(ModBlocks.VERTICAL_SAND_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RED_SAND_SLAB);
                        entries.add(ModBlocks.VERTICAL_RED_SAND_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_ICE_SLAB);
                        entries.add(ModBlocks.VERTICAL_ICE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PACKED_ICE_SLAB);
                        entries.add(ModBlocks.VERTICAL_PACKED_ICE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BLUE_ICE_SLAB);
                        entries.add(ModBlocks.VERTICAL_BLUE_ICE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SNOW_SLAB);
                        entries.add(ModBlocks.VERTICAL_SNOW_STAIRS);

                        entries.add(ModBlocks.VERTICAL_MOSS_SLAB);
                        entries.add(ModBlocks.VERTICAL_MOSS_STAIRS);
                        entries.add(ModBlocks.VERTICAL_PALE_MOSS_SLAB);
                        entries.add(ModBlocks.VERTICAL_PALE_MOSS_STAIRS);

                        entries.add(ModBlocks.VERTICAL_CALCITE_SLAB);
                        entries.add(ModBlocks.VERTICAL_CALCITE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DRIPSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DRIPSTONE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_MAGMA_SLAB);
                        entries.add(ModBlocks.VERTICAL_MAGMA_STAIRS);
                        entries.add(ModBlocks.VERTICAL_OBSIDIAN_SLAB);
                        entries.add(ModBlocks.VERTICAL_OBSIDIAN_STAIRS);
                        entries.add(ModBlocks.VERTICAL_CRYING_OBSIDIAN_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRYING_OBSIDIAN_STAIRS);

                        entries.add(ModBlocks.VERTICAL_CRIMSON_NYLIUM_SLAB);
                        entries.add(ModBlocks.VERTICAL_CRIMSON_NYLIUM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_WARPED_NYLIUM_SLAB);
                        entries.add(ModBlocks.VERTICAL_WARPED_NYLIUM_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SOUL_SAND_SLAB);
                        entries.add(ModBlocks.VERTICAL_SOUL_SAND_STAIRS);
                        entries.add(ModBlocks.VERTICAL_SOUL_SOIL_SLAB);
                        entries.add(ModBlocks.VERTICAL_SOUL_SOIL_STAIRS);
                        entries.add(ModBlocks.VERTICAL_BONE_BLOCK_SLAB);
                        entries.add(ModBlocks.VERTICAL_BONE_BLOCK_STAIRS);
                        
                        entries.add(ModBlocks.VERTICAL_COAL_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_COAL_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_COAL_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_COAL_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_IRON_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_IRON_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_IRON_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_IRON_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_COPPER_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_COPPER_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_COPPER_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_COPPER_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_GOLD_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_GOLD_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_GOLD_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_GOLD_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_REDSTONE_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_REDSTONE_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_REDSTONE_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_REDSTONE_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_EMERALD_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_EMERALD_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_EMERALD_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_EMERALD_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_LAPIS_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_LAPIS_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_LAPIS_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_LAPIS_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DIAMOND_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DIAMOND_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_DIAMOND_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_DEEPSLATE_DIAMOND_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_NETHER_GOLD_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_NETHER_GOLD_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_NETHER_QUARTZ_ORE_SLAB);
                        entries.add(ModBlocks.VERTICAL_NETHER_QUARTZ_ORE_STAIRS);
                        entries.add(ModBlocks.VERTICAL_ANCIENT_DEBRIS_SLAB);
                        entries.add(ModBlocks.VERTICAL_ANCIENT_DEBRIS_STAIRS);

                        entries.add(ModBlocks.VERTICAL_RAW_IRON_BLOCK_SLAB);
                        entries.add(ModBlocks.VERTICAL_RAW_IRON_BLOCK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RAW_COPPER_BLOCK_SLAB);
                        entries.add(ModBlocks.VERTICAL_RAW_COPPER_BLOCK_STAIRS);
                        entries.add(ModBlocks.VERTICAL_RAW_GOLD_BLOCK_SLAB);
                        entries.add(ModBlocks.VERTICAL_RAW_GOLD_BLOCK_STAIRS);

                        entries.add(ModBlocks.VERTICAL_GLOWSTONE_SLAB);
                        entries.add(ModBlocks.VERTICAL_GLOWSTONE_STAIRS);

                            })).build());


    public static void registerItemGroups() {
    }
}
